# Generated by Django 5.2.7 on 2025-10-30 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(choices=[('system', 'Système'), ('user', 'Utilisateur')], max_length=50)),
                ('contenu', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('emotions', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
