# Generated by Django 5.2.7 on 2025-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='emotions',
            new_name='emotions_local',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='emotions_gemini',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sentiment_gemini',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sentiment_local',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
