# Generated by Django 5.2.7 on 2025-10-30 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0002_rename_emotions_reclamation_emotions_local_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='emotions_gemini',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='emotions_local',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sentiment_gemini',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sentiment_local',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sujet',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='emotions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='cible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_recues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
