# Generated by Django 5.2.7 on 2025-10-30 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_remove_reclamation_contenu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
