# Generated by Django 5.2.7 on 2025-10-30 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0004_alter_reclamation_auteur_alter_reclamation_cible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='emotions',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='contenu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='emotions_local',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sentiment_local',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sujet',
            field=models.CharField(choices=[('system', 'Système'), ('user', 'Utilisateur')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
